# Generated by Django 4.2 on 2025-12-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
