# Generated by Django 4.2 on 2026-02-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_menuitem_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="menucategory",
            name="name_alternative",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="description_alternative",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="name_alternative",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
